### ISSUE TITLE
Missing parentheses in call to 'print' on Python 3.4.3 pip install

### ISSUE THREAD

**Issue by donnemartin** [avinassh/haxor#3]
Hi, I'm getting the following error trying to install on Python 3.4.3, but it works fine on 2.7.10:

    $ pip install haxor

```
Collecting haxor
  Using cached haxor-0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/rp/8nf53wk57bgd12w6fr31rrwh0000gn/T/pip-build-yuswawpl/haxor/setup.py", line 12
        print long_description
                             ^
    SyntaxError: Missing parentheses in call to 'print'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/rp/8nf53wk57bgd12w6fr31rrwh0000gn/T/pip-build-yuswawpl/haxor
```

**Comment by avinassh** [comment]
Fixed. Thanks for reporting :)

I have updated the `haxer` version on pypi, so try:

```shell
pip install --upgrade haxor --no-cache
```

**Comment by donnemartin** [comment]
Thanks for the quick fix! :+1:

**Comment by abiraja2004** [comment]
It really worked :) Thanks!!

**Comment by wosgec** [comment]
pip install pydoop, python 3.4.. showing parenthesis error to print....
